Issue 15 create predefined object
gideontong/biblepoet pull request #53
Opened 2024-06-25 06:55 UTC by nathansit

Closes #15

2024-06-25 07:08 UTC, nathansit commented
Lint not cooperating
But that will be tomorrow's problem

2024-06-25 12:14 UTC, gideontong commented on src/objects/booksOfTheBible.ts
> +const Genesis = new Book();
Please add the lint disabler

2024-06-25 12:14 UTC, gideontong requested changes

2024-06-25 12:14 UTC, gideontong commented on src/objects/booksOfTheBible.ts
> +// thank you Gemini
Please remove this comment

2024-06-25 12:14 UTC, gideontong commented on src/objects/booksOfTheBible.ts
> +// underscore in front of numbers to keep the naming convention consistent
Please change the names to Book_1

2024-06-25 20:44 UTC, gideontong requested changes
Almost

2024-06-25 20:44 UTC, gideontong commented on src/objects/booksOfTheBible.ts
> +/* eslint @typescript-eslint/no-unused-vars: 0 */
Please do not use global disables

2024-06-26 06:15 UTC, gideontong requested changes
You haven't made the requested changes. Also while you're at it, please rename the file to `objects/all.ts`

2024-06-26 06:18 UTC, gideontong commented
While you're at it, please also rename the PR title

2024-06-26 06:39 UTC, nathansit commented on src/objects/booksOfTheBible.ts
> +/* eslint @typescript-eslint/no-unused-vars: 0 */
I don't understand. I have dozens of unused variables atm. Would you rather have me use block comments to disable them, or modify the configuration file?

```
/* eslint-disable */

alert('foo');

/* eslint-enable */
```

2024-06-26 19:28 UTC, gideontong commented
You didn’t complete any of the requested changes. Going to close this PR tomorrow unless you update it as it’s now empty diff

2024-06-26 19:29 UTC, gideontong commented on src/objects/booksOfTheBible.ts
> +/* eslint @typescript-eslint/no-unused-vars: 0 */
Individual disable so that you don’t miss one later

2024-06-26 19:45 UTC, gideontong commented
Ok, just one more thing left to do

2024-06-27 05:19 UTC, gideontong commented
It's now an empty diff

2024-06-27 05:20 UTC, gideontong requested changes
It's now an empty diff

2024-06-27 15:58 UTC, gideontong commented
Please change the PR title to the issue title if you can, not a requirement

2024-06-27 16:21 UTC, nathansit commented
Bruh I did it again huhEnviado desde mi iPhoneEl jun 27, 2024, a la(s) 01:20, Gideon Tong ***@***.***> escribió:﻿
@gideontong requested changes on this pull request.

It's now an empty diff

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-07-03 20:07 UTC, gideontong approved these changes

2024-07-05 03:36 UTC, merged