add docstrings
gideontong/biblepoet pull request #67
Opened 2024-07-05 04:20 UTC by nathansit

Just annotating one class. If it looks good will add the rest
Closes #49

2024-07-05 04:27 UTC, gideontong requested changes
it's good enough

2024-07-05 04:27 UTC, gideontong commented on eslint.config.mjs
Let's not modify files that aren't part of the original issue unless there's a super good reason

2024-07-05 04:30 UTC, nathansit commented on eslint.config.mjs
I only changed it because `npx eslint .` was complaining

2024-07-05 04:47 UTC, nathansit commented on eslint.config.mjs
But ok I just reverted it

2024-07-05 05:51 UTC, gideontong requested changes

2024-07-05 05:51 UTC, gideontong commented on src/classes/Book.ts
> + * Represents a Book in the Bible
Lowercase book

2024-07-05 05:51 UTC, gideontong commented on src/classes/Book.ts
> + * @property {object} metadata data about Book
More specific description

2024-07-05 05:51 UTC, gideontong commented on src/classes/Chapter.ts
> + * A subunit of a Book
That's not really a true description

2024-07-05 05:51 UTC, gideontong commented on src/classes/Chapter.ts
> + * @property {object} metadata data about Chapter
More descriptive please

2024-07-05 05:51 UTC, gideontong commented on src/classes/Reference.ts
> + * Pointer to a related Passage from the Bible
This isn't true

2024-07-05 05:51 UTC, gideontong commented on src/classes/Verse.ts
> + * A subunit of Chapter, which is a subunit of Book
Try to use more descriptive language and not "subunit"

2024-07-05 05:51 UTC, gideontong commented on src/classes/Version.ts
> + * This class stores information to keep track of which is currently being used
That isn't true

2024-07-10 21:58 UTC, gideontong requested changes

2024-07-10 21:58 UTC, gideontong commented on src/classes/Passage.ts
> + * A set of one or more consecutive verses from the Bible
What exactly are we annotating here

2024-07-10 21:58 UTC, gideontong commented on src/classes/Chapter.ts
> + * A book of the Bible consists of one or more chapters. These manmade delineations divide
Be more clear you are describing a chapter

2024-07-10 21:58 UTC, gideontong commented on src/classes/Verse.ts
> + * A book is comprised of chapters. These chapters can be further divided into verses.
Be more clear you're describing a verse

2024-07-10 21:58 UTC, gideontong commented on src/classes/Version.ts
> + * The Bible has many different Versions across different translations.
Do not capitalize versions unless it is exactly the class name?

2024-07-10 21:59 UTC, gideontong commented
Sorry I didn't get to this earlier, next time you can request review so I get a notification as I never got a notification.

2024-07-19 03:52 UTC, nathansit commented
push

2024-07-29 04:09 UTC, nathansit commented
make unstable

2024-08-11 02:25 UTC, closed without merging